apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dsapp
spec:

  selector:
    matchLabels:
      app: ds-nginx

  template:
    metadata:
      labels:
        app: ds-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80